/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private java.util.ArrayList<Veiculo> listaVeiculos = new java.util.ArrayList<>();
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motocicleta", "Onibus ", "Automovel", "SUV", "Caminhonete" }));

        jLabel1.setText("Nome:");

        jLabel2.setText("Fabricante:");

        jLabel3.setText("Preço:");

        jLabel4.setText("Atributo Especifico:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Nome", "Fabricante", "Preço Venda", "Atributo Esp.", "IPVA(R$)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Adicionar Veiculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor total do IPVA da frota:R$0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4))
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        // 1. Validação: Impede que o programa rebente se o utilizador deixar campos em branco
        if (jTextField1.getText().trim().isEmpty() || 
            jTextField2.getText().trim().isEmpty() ||
            jTextField3.getText().trim().isEmpty() || 
            jTextField4.getText().trim().isEmpty()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, preencha todos os campos (Nome, Fabricante, Preço e Atributo) antes de adicionar.", 
                "Campos Vazios", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Captura os dados gerais (comuns a todos os veículos)
        String tipo = (String) jComboBox1.getSelectedItem(); 
        String nome = jTextField1.getText().trim();                 
        String fabricante = jTextField2.getText().trim();
        
        // Trata o preço substituindo a vírgula por ponto (evita erros se digitarem 45000,50)
        double preco = Double.parseDouble(jTextField3.getText().replace(",", "."));
        
        // Captura o atributo numérico específico (cilindradas, passageiros ou potência)
        int atributoEspecifico = Integer.parseInt(jTextField4.getText().trim());

        // 3. Polimorfismo: Cria uma referência da classe mãe (Veiculo)
        Veiculo novoVeiculo = null;

        // O .trim() garante que o texto do ComboBox bate certinho com o switch cas

        // O .trim() garante que o texto do ComboBox bate certinho com o switch case
        switch (tipo.trim()) {
            case "Motocicleta":
                novoVeiculo = new Motocicleta(nome, fabricante, preco, atributoEspecifico);
                break;
            case "Onibus":
                novoVeiculo = new Onibus(nome, fabricante, preco, atributoEspecifico);
                break;
            case "Automovel":
                novoVeiculo = new Automovel(nome, fabricante, preco, atributoEspecifico);
                break;
            case "SUV":
                novoVeiculo = new Suv(nome, fabricante, preco, atributoEspecifico);
                break;
            case "Caminhonete":
                novoVeiculo = new Caminhonete(nome, fabricante, preco, atributoEspecifico);
                break;
            default:
                javax.swing.JOptionPane.showMessageDialog(this, "Tipo de veículo inválido.");
                return;
        }

        // 4. Se o veículo foi criado corretamente, insere na lista e na tabela
        if (novoVeiculo != null) {
            // Guarda no ArrayList global que criaste (listaVeiculos) 
            listaVeiculos.add(novoVeiculo);
            
            // Puxa o modelo de dados da tua JTable para adicionar a linha
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            
            // Remove aquelas 4 linhas vazias padrões do NetBeans assim que adicionas o primeiro veículo
            if (modelo.getRowCount() > 0 && modelo.getValueAt(0, 0) == null) {
                modelo.setRowCount(0);
            }
            
            // Insere a linha visual na tabela com o toString() do tipo e o IPVA calculado por classe 
            modelo.addRow(new Object[]{
                novoVeiculo.toString(), // Retorna "Motocicleta", "Onibus", "SUV", etc. [cite: 18, 46, 57]
                novoVeiculo.getNome(),
                novoVeiculo.getFabricante(),
                String.format("R$ %.2f", novoVeiculo.getPrecoVenda()),
                atributoEspecifico,
                String.format("R$ %.2f", novoVeiculo.calcularIPVA()) // Executa a fórmula certa de cada classe [cite: 15, 18, 46, 57]
            });

            // 5. Percorre o ArrayList e calcula a soma total de IPVA de toda a frota 
            double totalIPVA = 0;
            for (Veiculo v : listaVeiculos) {
                totalIPVA += v.calcularIPVA();
            }
            
            // Exibe o total formatado no jLabel5 (o label do resultado) 
            jLabel5.setText(String.format("Valor total do IPVA da frota: R$ %.2f", totalIPVA));
            
            // 6. Limpa todos os campos para o utilizador cadastrar o próximo
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField1.requestFocus(); // Coloca o cursor a piscar diretamente no campo "Nome"
        }
        
    } catch (NumberFormatException ex) {
        // Se o utilizador digitar letras nos campos de Preço ou Atributo Específico
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Erro de Digitação:\n- O campo 'Preço' aceita apenas números (ex: 35000.00).\n- O campo 'Atributo Específico' aceita apenas números inteiros (ex: 125, 45, 180).", 
            "Formato Inválido", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        // Captura qualquer outro imprevisto e exibe na tela sem fechar a aplicação
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Ocorreu um erro inesperado: " + ex.getMessage(), 
            "Erro", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
